### ISSUE TITLE
panic on ShowBodyOnly 

### ISSUE THREAD

**Issue by greygore** [JalfResi/GoTidy#6]
Trying to set ShowBodyOnly:

``` go
    t := tidy.New()
    t.ShowBodyOnly(1)
```

But it results in a panic:

```
Assertion failed: (option_defs[ optId ].type == TidyInteger), function SetOptionInt, file ../../src/config.c, line 381.
SIGABRT: abort
PC=0x7fff8782e002 m=6
signal arrived during cgo execution

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x42fed20, 0xc8200b1740, 0x0)
    /usr/local/Cellar/go/1.5.3/libexec/src/runtime/cgocall.go:120 +0x11b fp=0xc8200b16f0 sp=0xc8200b16c0
github.com/JalfResi/GoTidy._Cfunc_tidyOptSetInt(0x5804200, 0xc80000003b, 0x1, 0xc800000000)
    ??:0 +0x39 fp=0xc8200b1740 sp=0xc8200b16f0
github.com/JalfResi/GoTidy.(*Tidy).optSetInt(0xc820330540, 0xc80000003b, 0x1, 0xc820015f80, 0x0, 0x0)
    /usr/local/lib/go/src/github.com/JalfResi/GoTidy/options.go:543 +0x42 fp=0xc8200b1768 sp=0xc8200b1740
github.com/JalfResi/GoTidy.(*Tidy).optSetAutoBool(0xc820330540, 0xc80000003b, 0x1, 0x5804200, 0x0, 0x0)
    /usr/local/lib/go/src/github.com/JalfResi/GoTidy/options.go:530 +0x4f fp=0xc8200b17c8 sp=0xc8200b1768
github.com/JalfResi/GoTidy.(*Tidy).ShowBodyOnly(0xc820330540, 0x1, 0xc8200b18a8, 0x0, 0x0)
    /usr/local/lib/go/src/github.com/JalfResi/GoTidy/options.go:260 +0x3f fp=0xc8200b1800 sp=0xc8200b17c8
```

**Comment by JalfResi** [comment]
Thanks for this! Hopefully I can find time to fix this on the weekend
